# Generated by Django 6.0.5 on 2026-07-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=300)),
                ('foto', models.ImageField(upload_to='atores/')),
                ('nasc', models.CharField(max_length=300)),
                ('resumo', models.TextField()),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Criadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=300)),
                ('foto', models.ImageField(upload_to='criadores/')),
                ('nasc', models.CharField(max_length=300)),
                ('resumo', models.TextField()),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sinopse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('sinopse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='devs/')),
                ('curiosidade', models.TextField()),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
